import pandas as pd
import os
from fpdf import FPDF
from datetime import datetime

INPUT_FILE = "2025_CARBON_RISK_SCREENED.csv"
OUTPUT_DIR = "memos"
PROJECT_NAME = "Public Procurement Carbon Risk Screen (PP-CRS)"

# Ensure output directory exists
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)


class ForensicMemo(FPDF):
    # Fixed header applied to every memo page
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'CONFIDENTIAL: FORENSIC CARBON SCREEN', 0, 1, 'C')
        self.ln(5)

    # Fixed footer for provenance and attribution
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(
            0,
            10,
            f'Generated by {PROJECT_NAME} | Open Source Research',
            0,
            0,
            'C'
        )


def generate_pdf(row):
    pdf = ForensicMemo()
    pdf.add_page()

    # Memo identity
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, f"Memo: {row['buyer_name']}", 0, 1)

    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d')}", 0, 1)
    pdf.ln(5)

    # Executive summary (non-technical, decision-facing)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "1. Executive Summary", 0, 1)
    pdf.set_font('Arial', '', 11)

    summary_text = (
        f"A forensic screen of open public procurement data identified the contract "
        f"'{row['title']}' as a Critical Carbon Priority.\n\n"
        f"Based on the contract value (£{row['value_amount']:,.2f}) and detected material profile "
        f"({row['detected_material_name']}), we estimate the embodied carbon risk "
        f"to be approximately {row['est_co2e_tonnes']:,.0f} tonnes CO2e."
    )
    pdf.multi_cell(0, 7, summary_text)
    pdf.ln(5)

    # Transparent calculation section (audit-safe)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "2. Forensic Calculation Method", 0, 1)
    pdf.set_font('Arial', '', 10)

    spend = float(row['value_amount'])
    price = float(row['applied_price_rate'])
    mass = float(row['est_material_tonnes'])
    factor = float(row['applied_carbon_factor'])

    calc_text = (
        f"Methodology: High-fidelity screening using industry composite rates (SPONS 2024) "
        f"and emission factors (ICE V4.1 / DEFRA 2025).\n\n"
        f"A. Contract Value:      £{spend:,.2f}\n"
        f"B. Composite Rate:      £{price:.2f} per tonne (Installed)\n"
        f"C. Est. Quantity:       {mass:,.0f} tonnes ({row['detected_material_name']})\n"
        f"D. Emission Factor:     {factor:.2f} kgCO2e/tonne ({row['data_source_ref']})\n\n"
        f"CALCULATION: ({mass:,.0f} tonnes × {factor:.2f} kg/t) / 1000 "
        f"= {row['est_co2e_tonnes']:,.2f} tonnes CO2e"
    )
    pdf.multi_cell(0, 6, calc_text)
    pdf.ln(10)

    # Action-oriented mitigation guidance
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "3. Mitigation Opportunities", 0, 1)
    pdf.set_font('Arial', '', 11)

    rec_text = "Standard interventions for this material profile:"
    if "Asphalt" in row['detected_material_name']:
        rec_text += (
            "\n- Switch to Warm Mix Asphalt (WMA) for ~15% carbon reduction."
            "\n- Increase Recycled Asphalt Pavement (RAP) content."
        )
    elif "Concrete" in row['detected_material_name']:
        rec_text += (
            "\n- Specify CEM II/III (GGBS or PFA substitution)."
            "\n- Review structural over-design."
        )
    elif "Steel" in row['detected_material_name']:
        rec_text += (
            "\n- Require EAF steel over BOS routes."
            "\n- Assess reuse and recovery potential."
        )
    else:
        rec_text += "\n- Request verified Environmental Product Declarations (EPDs)."

    pdf.multi_cell(0, 7, rec_text)
    pdf.ln(10)

    # Legal and methodological limitation
    pdf.set_font('Arial', 'I', 8)
    disclaimer = (
        "DISCLAIMER: This is a screening-level estimate derived from open procurement data. "
        "Quantities are inferred using heuristic models and do not replace a Bill of Quantities. "
        "For prioritisation purposes only."
    )
    pdf.multi_cell(0, 5, disclaimer)

    # File-safe output name
    safe_name = "".join(
        c for c in row['buyer_name']
        if c.isalnum() or c == ' '
    ).strip()
    filename = f"{OUTPUT_DIR}/Memo_{safe_name.replace(' ', '_')}.pdf"

    pdf.output(filename)
    return filename


def run_memo_generator():
    # Locate screened output dynamically
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_path = None

    for root, _, files in os.walk(os.path.dirname(script_dir)):
        if INPUT_FILE in files:
            input_path = os.path.join(root, INPUT_FILE)
            break

    if not input_path:
        print(f"Error: Could not find {INPUT_FILE}")
        return

    print(f"--- Generating Forensic Memos from {input_path} ---")
    df = pd.read_csv(input_path)

    # Highest-risk contracts only
    top_risks = df.head(3)

    for _, row in top_risks.iterrows():
        # Console audit for traceability
        print(f"\nAUDIT: {row['buyer_name']}")
        print(f"  Spend: £{row['value_amount']}")
        print(f"  Rate:  £{row['applied_price_rate']} / t")
        print(f"  EF:    {row['applied_carbon_factor']} kgCO2e/t")
        print(f"  Total: {row['est_co2e_tonnes']} tCO2e")

        try:
            filename = generate_pdf(row)
            print(f"  PDF Created: {filename}")
        except Exception as e:
            print(f"  PDF Failed: {e}")


if __name__ == "__main__":
    run_memo_generator()
