import pandas as pd
import os
from fpdf import FPDF
from datetime import datetime 

# --- CONFIGURATION ---
INPUT_FILE = "2025_CARBON_RISK_SCREENED.csv"
OUTPUT_DIR = "memos"
PROJECT_NAME = "Public Procurement Carbon Risk Screen (PP-CRS)"

# Ensure output directory exists
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

class ForensicMemo(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'CONFIDENTIAL: FORENSIC CARBON SCREEN', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by {PROJECT_NAME} | Open Source Research', 0, 0, 'C')

def generate_pdf(row):
    pdf = ForensicMemo()
    pdf.add_page()
    
    # 1. HEADER INFO
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, f"Memo: {row['buyer_name']}", 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d')}", 0, 1)
    pdf.ln(5)

    # 2. EXECUTIVE SUMMARY
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "1. Executive Summary", 0, 1)
    pdf.set_font('Arial', '', 11)
    
    summary_text = (
        f"A forensic screen of open public procurement data identified the contract "
        f"'{row['title']}' as a Critical Carbon Priority.\n\n"
        f"Based on the contract value (£{row['value_amount']:,.2f}) and detected material profile "
        f"({row['detected_material_name']}), we estimate the embodied carbon risk "
        f"to be approximately {row['est_co2e_tonnes']:,.0f} tonnes CO2e."
    )
    pdf.multi_cell(0, 7, summary_text)
    pdf.ln(5)

    # 3. THE CALCULATION (Show your work)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "2. Forensic Calculation Method", 0, 1)
    pdf.set_font('Arial', '', 10)
    
    # Extract numbers for clear display
    spend = float(row['value_amount'])
    price = float(row['applied_price_rate'])
    mass = float(row['est_material_tonnes'])
    factor = float(row['applied_carbon_factor'])
    
    calc_text = (
        f"Methodology: High-fidelity screening using industry composite rates (SPONS 2024) "
        f"and emission factors (ICE V4.1 / DEFRA 2025).\n\n"
        f"A. Contract Value:      £{spend:,.2f}\n"
        f"B. Composite Rate:      £{price:.2f} per tonne (Installed)\n"
        f"C. Est. Quantity:       {mass:,.0f} tonnes ({row['detected_material_name']})\n"
        f"D. Emission Factor:     {factor:.2f} kgCO2e/tonne ({row['data_source_ref']})\n\n"
        f"CALCULATION: ({mass:,.0f} tonnes * {factor:.2f} kg/t) / 1000 = {row['est_co2e_tonnes']:,.2f} tonnes CO2e"
    )
    pdf.multi_cell(0, 6, calc_text)
    pdf.ln(10)

    # 4. RECOMMENDATION
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "3. Mitigation Opportunities", 0, 1)
    pdf.set_font('Arial', '', 11)
    
    rec_text = "Standard interventions for this material profile:"
    if "Asphalt" in row['detected_material_name']:
        rec_text += "\n- Switch to Warm Mix Asphalt (WMA) for ~15% carbon reduction.\n- Increase Recycled Asphalt Pavement (RAP) content in binder course."
    elif "Concrete" in row['detected_material_name']:
        rec_text += "\n- Specify CEM II/III (GGBS/PFA replacements) to lower cement content.\n- Review structural over-design."
    elif "Steel" in row['detected_material_name']:
        rec_text += "\n- Require EAF (Electric Arc Furnace) steel over BOS (Basic Oxygen Steel).\n- Audit reuse potential."
    else:
        rec_text += "\n- Request Environmental Product Declarations (EPDs) from Tier 1 suppliers."
        
    pdf.multi_cell(0, 7, rec_text)
    pdf.ln(10)
    
    # 5. DISCLAIMER
    pdf.set_font('Arial', 'I', 8)
    disclaimer = (
        "DISCLAIMER: This report is a screening estimate based on open data (Contracts Finder). "
        "It applies heuristic modeling to estimate quantities and does not replace a Bill of Quantities. "
        "Intended for internal prioritization use only."
    )
    pdf.multi_cell(0, 5, disclaimer)

    # Save
    safe_name = "".join([c for c in row['buyer_name'] if c.isalpha() or c.isdigit() or c==' ']).strip()
    filename = f"{OUTPUT_DIR}/Memo_{safe_name.replace(' ', '_')}.pdf"
    pdf.output(filename)
    return filename

def run_memo_generator():
    # Find the input file (reusing your dynamic logic)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Search for the file
    input_path = None
    for root, dirs, files in os.walk(os.path.dirname(script_dir)):
        if INPUT_FILE in files:
            input_path = os.path.join(root, INPUT_FILE)
            break
            
    if not input_path:
        print(f"Error: Could not find {INPUT_FILE}")
        return

    print(f"--- Generating Forensic Memos from {input_path} ---")
    df = pd.read_csv(input_path)
    
    # Take top 3 High Risk items
    top_risks = df.head(3)
    
    for index, row in top_risks.iterrows():
        # --- MATH AUDIT (CHECK THIS IN TERMINAL) ---
        print(f"\n AUDIT: {row['buyer_name']}")
        print(f"   Spend: £{row['value_amount']}")
        print(f"   Price/t: £{row['applied_price_rate']}")
        print(f"   Carb/t: {row['applied_carbon_factor']} kg")
        print(f"   Result: {row['est_co2e_tonnes']} tonnes CO2e")
        
        # Generate PDF
        try:
            filename = generate_pdf(row)
            print(f"   PDF Created: {filename}")
        except Exception as e:
            print(f"   PDF Failed: {e}")

if __name__ == "__main__":
    run_memo_generator()